### ISSUE TITLE
Ruby 3.2: Failed to build gem native extension

### ISSUE THREAD

**Issue by v-lunyov-ep** [instructure/nokogiri-xmlsec-instructure#18]
On Linux ARM64 (Docker image from `ruby:3.2.2-alpine`) i'm trying to run `bundle install` using Ruby 3.2 and get the following output (also using `ldflags` from the older closed issue here but it didn't help):

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /opt/bundler-cache/ruby/3.2.0/gems/nokogiri-xmlsec-instructure-0.10.2/ext/nokogiri_ext_xmlsec
/usr/local/bin/ruby extconf.rb --with-ldflags\=-Wl,-undefined,dynamic_lookup
checking for ruby.h... yes
Clfags: $(cflags)  -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_FTP=1 -DXMLSEC_NO_MD5=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1
-D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_FTP=1 -DXMLSEC_NO_MD5=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -I/usr/include/xmlsec1 -I/usr/include/libxml2
-DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -fvisibility=hidden -I/opt/bundler-cache/ruby/3.2.0/gems/nokogiri-1.15.4-x86_64-linux/ext/nokogiri
creating Makefile

current directory: /opt/bundler-cache/ruby/3.2.0/gems/nokogiri-xmlsec-instructure-0.10.2/ext/nokogiri_ext_xmlsec
make DESTDIR\= sitearchdir\=./.gem.20231023-22-2tzfwm sitelibdir\=./.gem.20231023-22-2tzfwm clean

current directory: /opt/bundler-cache/ruby/3.2.0/gems/nokogiri-xmlsec-instructure-0.10.2/ext/nokogiri_ext_xmlsec
make DESTDIR\= sitearchdir\=./.gem.20231023-22-2tzfwm sitelibdir\=./.gem.20231023-22-2tzfwm
compiling init.c
In file included from xmlsecrb.h:23,
                 from init.c:1:
/opt/bundler-cache/ruby/3.2.0/gems/nokogiri-1.15.4-x86_64-linux/ext/nokogiri/nokogiri.h:220:5: warning: "HAVE_RB_CATEGORY_WARNING" is not defined, evaluates to 0 [-Wundef]
  220 | #if HAVE_RB_CATEGORY_WARNING
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
init.c: In function 'Init_nokogiri_ext_xmlsec':
init.c:13:6: warning: old-style function definition [-Wold-style-definition]
   13 | void Init_nokogiri_ext_xmlsec() {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~
init.c:50:43: error: 'XMLSEC_CRYPTO' undeclared (first use in this function)
   50 |     if(xmlSecCryptoDLLoadLibrary(BAD_CAST XMLSEC_CRYPTO) < 0) {
      |                                           ^~~~~~~~~~~~~
init.c:50:43: note: each undeclared identifier is reported only once for each function it appears in
At top level:
cc1: note: unrecognized command-line option '-Wno-self-assign' may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option '-Wno-parentheses-equality' may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option '-Wno-constant-logical-operand' may have been intended to silence earlier diagnostics
make: *** [Makefile:248: init.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/bundler-cache/ruby/3.2.0/gems/nokogiri-xmlsec-instructure-0.10.2 for inspection.
Results logged to /opt/bundler-cache/ruby/3.2.0/extensions/x86_64-linux-musl/3.2.0/nokogiri-xmlsec-instructure-0.10.2/gem_make.out

  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:120:in `run'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:53:in `block in make'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:45:in `each'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:45:in `make'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:188:in `build_extension'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:222:in `block in build_extensions'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:219:in `each'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:219:in `build_extensions'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:844:in `build_extensions'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/source/rubygems.rb:202:in `install'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/installer/gem_installer.rb:54:in `install'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/worker.rb:62:in `apply_func'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/worker.rb:57:in `block in process_queue'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/worker.rb:54:in `loop'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/worker.rb:54:in `process_queue'
  /opt/bundler-cache/ruby/3.2.0/gems/bundler-2.4.18/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing nokogiri-xmlsec-instructure (0.10.2), and Bundler cannot continue.
```

i would appreciate any help with making this work as i'm now stuck for a bit while on a working project so big thanks in advance!

**Comment by v-lunyov-ep** [comment]
@ccutrer thank you for the information! it seems to be an issue for 3.1 as well. so i'm going with 3.0.6 for now with my Ruby upgrade, thanks again 🙂

**Comment by ahamana** [comment]
@v-lunyov-ep 
"XMLSEC_CRYPTO" has been deprecated since xmlsec 1.2.21 and it was removed in 1.3.0. (Alpine 3.18 or later)
So, the package needs to be installed by specifying the version that can refer to "XMLSEC_CRYPTO" to build "nokogiri-xmlsec-instructor".
e.g)
```
apk add --no-cache --repository https://dl-cdn.alpinelinux.org/alpine/v3.17/community/ \
    xmlsec-dev~=1.2
```
- https://github.com/ahamana/canvas-lms-docker/blob/main/Dockerfile-alpine#L28

**Comment by ahamana** [comment]
@ccutrer 
Many thanks for #20!
